# Generated by Django 4.1.1 on 2022-09-24 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_todolistitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolistitem",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 24, 14, 19, 46, 206108)
            ),
        ),
        migrations.AddField(
            model_name="todolistitem",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
