# Generated by Django 4.1.1 on 2022-09-24 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0003_todolistitem_create_date_todolistitem_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolistitem",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 24, 14, 21, 9, 723857)
            ),
        ),
    ]
