# Generated by Django 4.1.1 on 2022-09-24 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0004_alter_todolistitem_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolistitem",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todolistitem",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 24, 14, 22, 4, 851400)
            ),
        ),
    ]
