# Generated by Django 4.1.1 on 2022-09-24 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0005_todolistitem_time_alter_todolistitem_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolistitem",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 24, 15, 51, 57, 779729)
            ),
        ),
    ]
