# Generated by Django 4.1.1 on 2022-09-24 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0006_alter_todolistitem_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolistitem",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todolistitem",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 9, 24, 16, 54, 20, 478889)
            ),
        ),
    ]
